apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 400Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: io.rancher.longhorn
    fsType: ext4
    volumeHandle: jenkins-pv
